/**
 * Created by root on 16-12-1.
 */
// export const CHANGE_SHOW_FOR_DIALOG = 'CHANGE_SHOW_FOR_DIALOG'
export const CHANGE_LOADING = 'CHANGE_LOADING'
export const CHANGE_DIRECTION = 'CHANGE_DIRECTION'
export const SHOW_SEARCH_BOX = 'SHOW_SEARCH_BOX'
export const CLOSE_SEARCH_BOX = 'CLOSE_SEARCH_BOX'
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS'
export const SET_SEARCH_TEXT_FIELD_VALUE = 'SET_SEARCH_TEXT_FIELD_VALUE'
