/**
 * Created by root on 16-12-1.
 */
// export const CHANGE_SHOW_FOR_DIALOG = 'CHANGE_SHOW_FOR_DIALOG'
export const CHANGE_LOADING = 'CHANGE_LOADING'
export const CHANGE_DIRECTION = 'CHANGE_DIRECTION'
export const SHOW_SEARCH_BOX = 'SHOW_SEARCH_BOX'
export const CLOSE_SEARCH_BOX = 'CLOSE_SEARCH_BOX'
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS'
export const SET_SEARCH_TEXT_FIELD_VALUE = 'SET_SEARCH_TEXT_FIELD_VALUE'
export const SET_TOP_BAR_ICON_MENU = 'SET_TOP_BAR_ICON_MENU'
export const SET_TOP_BAR_ICON_MENU_ICON = 'SET_TOP_BAR_ICON_MENU_ICON'
export const SET_TOP_BAR_ICON_MENU_CURRENT_VALUE = 'SET_TOP_BAR_ICON_MENU_CURRENT_VALUE'
export const SET_TOP_BAR_ICON_MENU_TYPE = 'SET_TOP_BAR_ICON_MENU_TYPE'

/* route page and getOrder page */
export const SET_ORDER_PREPARING_DATA_FOR_ROUTE = 'SET_ORDER_PREPARING_DATA_FOR_ROUTE'
export const CLEAR_PREPARING_DATA_FOR_ROUTE = 'CLEAR_PREPARING_DATA_FOR_ROUTE'
export const SET_ORDER_WARE_ID = 'SET_ORDER_WARE_ID'
export const SET_ORDER_TARGET_ADDRESS = 'SET_ORDER_TARGET_ADDRESS'
export const SET_ORDER_TARGET_DISTRIBUTE  = 'SET_ORDER_TARGET_DISTRIBUTE'
export const SET_ORDER_STATION  = 'SET_ORDER_STATION'
export const SET_ORDER_GENERAL  = 'SET_ORDER_GENERAL'
export const SET_ORDER_LOGISTICAL = 'SET_ORDER_LOGISTICAL'

export const SET_ORDER = 'SET_ORDER'

/* factory */
export const SET_SHIPMENT_DATA_FOR_FACTORY = 'SET_SHIPMENT_DATA_FOR_FACTORY'

/* orders */
export const SET_ORDERS_FOR_ORDERS_MANAGER = 'SET_ORDERS_FOR_ORDERS_MANAGER'

/* dialog */
export const SET_GENERAL_DIALOG = 'SET_GENERAL_DIALOG'
